version: '3'

services:
  app-base: &app-base
    build:
      context: .
      dockerfile: ./node/Dockerfile
    working_dir: /var/www
    volumes:
      - ./src:/var/www
      - /var/www/node_modules
    stdin_open: true
    tty: true

  watch:
    <<: *app-base
    command: yarn watch
    depends_on:
      - db

  app:
    <<: *app-base
    ports:
      - 3000:3000
    command: yarn dev
    depends_on:
      - db

  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - 80:80
    volumes:
      - ./src:/var/www
      - ./nginx/log:/var/log/nginx/
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - app
      - db

  db:
    image: postgres:13-alpine
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: db_dev
      TZ: 'Asia/Tokyo'
    volumes:
      - ./postgresql:/var/lib/postgresql
    ports:
      - 5432:5432
