version: '3'

services:
  app-base:
    image: node:12-alpine
    working_dir: /var/www
    volumes:
      - ./src:/var/www
    stdin_open: true
    tty: true

  install:
    extends:
      service: app-base
    working_dir: /var/www/testapp
    command: yarn install

  app:
    extends:
      service: app-base
    working_dir: /var/www/testapp
    ports:
      - 3000:3000
    command: yarn start dev
    depends_on:
      - db

  nginx:
    image: nginx:alpine
    ports:
      - 80:80
    volumes:
      - ./src:/var/www
      - ./docker/nginx/log:/var/log/nginx/
      - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
    - app
    - db

  db:
    image: postgres:13-alpine
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: db_dev
      TZ: 'Asia/Tokyo'
    volumes:
      - .docker/db/data:/var/lib/postgresql/data
    ports:
      - 5432:5432
